spring:
  application:
    name: spring
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  mail:
    host: smtp.gmail.com
    port: 587
    username: kau.hearday@gmail.com
    password: ${GOOGLE_APP_PASSWORD}
    properties:
      mail:
        smtp:
          ssl:
            trust: smtp.gmail.com
          auth: true
          starttls:
            enable: true
#jwt:
#  token:
#    secretKey: heardayjwttokenauthentication
#    expiration:
#      access: 14400000