spring:
  application:
    name: spring
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  mail:
    host: smtp.gmail.com
    port: 587
    username: kau.hearday@gmail.com
    password: ${GOOGLE_APP_PASSWORD}
    properties:
      mail:
        smtp:
          ssl:
            trust: smtp.gmail.com
          auth: true
          starttls:
            enable: true
dictionary:
  api:
    key: ${DIC_API_KEY}
jwt:
  secret:
    key: ${JWT_SECRET_KEY}
kakao:
  auth:
    client: ${KAKAO_CLIENT_ID}
    redirect: ${KAKAO_REDIRECT_URL}