-- test-data.sql

-- ArticleDetail 더미 데이터 먼저 생성 (20개)
INSERT INTO article_detail (content, created_at, tts_url, updated_at) VALUES
                                                                 ('사람 예능 영차 공급 부족 전자미 아예 추석 거치 예매 당황이 유난히 차질해졌습니다. 많은 분들이 불편을 겪고 계시는데요, 이에 대한 해결 방법을 알아보겠습니다. 첫째, 새벽 시간대를 노려보세요. 둘째, 모바일 앱을 활용하세요. 셋째, 대체 교통수단을 고려해보세요.', NOW(), 'https://s3/tts-url/tts.mp3',NOW()),
                                                                 ('임의의 플립의 하는 방법약 으로플로프리온이 FDA 신속 상녀 만큼 승인 가능성 거버너다. 특별 할인 이벤트가 진행 중입니다. 이번 기회를 놓치지 마세요! 최대 20% 할인 혜택과 함께 다양한 사은품을 제공합니다.', NOW(), 'https://s3/tts-url/tts.mp3',NOW()),
                                                                 ('최근 AI 코딩 도구들이 급속도로 발전하고 있습니다. GitHub Copilot, ChatGPT, Claude 등 다양한 도구들의 장단점을 비교 분석해보았습니다. 각 도구의 특징과 사용 시나리오에 따른 추천 사항을 정리했습니다. 개발 생산성 향상을 위한 최적의 선택을 해보세요.', NOW(), 'https://s3/tts-url/tts.mp3',NOW()),
                                                                 ('새로운 제품이 출시되었습니다! 혁신적인 기능과 세련된 디자인으로 여러분을 찾아갑니다. 사전 예약 고객에게는 특별한 혜택이 제공됩니다. 지금 바로 확인해보세요. 한정 수량으로 준비되어 있으니 서둘러 주세요.', NOW(), 'https://s3/tts-url/tts.mp3',NOW()),
                                                                 ('스프링 부트 애플리케이션의 성능을 최적화하는 다양한 방법을 소개합니다. 1. 데이터베이스 쿼리 최적화: N+1 문제 해결, 인덱스 활용 2. 캐싱 전략: Redis, Caffeine 활용 3. 비동기 처리: @Async, CompletableFuture 4. 커넥션 풀 튜닝 5. JVM 옵션 최적화. 각 항목별 상세한 예제 코드와 함께 실무에서 바로 적용 가능한 팁들을 공유합니다.', NOW(), 'https://s3/tts-url/tts.mp3',NOW()),
                                                                 ('Java 17의 주요 신규 기능들을 정리했습니다. Sealed Classes로 클래스 계층 구조를 제한하고, Pattern Matching for instanceof로 코드를 간결하게 만들 수 있습니다. Text Blocks를 사용하면 여러 줄 문자열을 쉽게 작성할 수 있습니다. Records를 활용한 불변 데이터 클래스 생성 방법도 소개합니다.', NOW(), 'https://s3/tts-url/tts.mp3',NOW()),
                                                                 ('가을을 맞아 특별한 세일 이벤트를 진행합니다. 최대 50% 할인과 무료 배송 혜택을 놓치지 마세요! 모든 제품이 대상이며, 추가로 포인트 적립도 2배로 제공됩니다. 이번 기회에 장바구니에 담아두었던 상품들을 구매해보세요.', NOW(), 'https://s3/tts-url/tts.mp3',NOW()),
                                                                 ('Docker 컨테이너의 크기를 줄이고 실행 속도를 높이는 방법을 소개합니다. Multi-stage build를 활용하여 최종 이미지 크기를 최소화하고, Alpine Linux 기반 이미지를 사용하여 보안을 강화하세요. .dockerignore 파일로 불필요한 파일을 제외하고, 레이어 캐싱을 최적화하는 방법도 다룹니다.', NOW(), 'https://s3/tts-url/tts.mp3',NOW()),
                                                                 ('ChatGPT를 효과적으로 활용하는 방법을 정리했습니다. 프롬프트 작성 팁부터 실무 적용 사례까지 상세히 다룹니다. 명확한 지시사항 작성, 예시 제공, 역할 부여 등의 기법을 활용하면 더 좋은 결과를 얻을 수 있습니다. 코드 리뷰, 문서 작성, 아이디어 브레인스토밍 등 다양한 활용 사례를 소개합니다.', NOW(), 'https://s3/tts-url/tts.mp3',NOW()),
                                                                 ('새로운 제품 라인업이 공개되었습니다. 혁신적인 디자인과 강력한 성능을 경험해보세요. 사전 예약을 통해 특별 할인 혜택을 받으실 수 있으며, 선착순 100명에게는 추가 사은품을 증정합니다. 출시 예정일은 다음 달 15일입니다.', NOW(), 'https://s3/tts-url/tts.mp3',NOW()),
                                                                 ('Kubernetes 초보자를 위한 입문 가이드입니다. 설치부터 배포까지 단계별로 설명합니다. Pod, Service, Deployment 등 기본 개념을 이해하고, kubectl 명령어 사용법을 익혀보세요. 실습 예제를 통해 실제 애플리케이션을 배포하는 방법을 학습할 수 있습니다.', NOW(), 'https://s3/tts-url/tts.mp3',NOW()),
                                                                 ('개발자로 성장하기 위한 학습 로드맵을 제시합니다. 프론트엔드, 백엔드, DevOps 각 분야별 추천 학습 경로를 소개합니다. 초급부터 고급까지 단계별로 학습해야 할 기술 스택과 추천 학습 자료를 정리했습니다. 실무 프로젝트 경험을 쌓는 방법도 함께 다룹니다.', NOW(), 'https://s3/tts-url/tts.mp3',NOW()),
                                                                 ('올 한해를 마무리하는 특별한 세일! 모든 제품 대폭 할인 중입니다. 연말 결산을 맞아 재고 정리를 위한 파격 할인을 진행합니다. 최대 70% 할인된 가격으로 만나보세요. 12월 31일까지 한정 판매이니 서둘러 주세요!', NOW(), 'https://s3/tts-url/tts.mp3',NOW()),
                                                                 ('GraphQL과 REST API의 장단점을 비교 분석합니다. GraphQL은 클라이언트가 필요한 데이터만 요청할 수 있어 효율적이지만, 캐싱이 복잡합니다. REST API는 표준화되어 있고 캐싱이 쉽지만, Over-fetching이나 Under-fetching 문제가 있을 수 있습니다. 프로젝트 특성에 맞는 최적의 선택을 도와드립니다.', NOW(), 'https://s3/tts-url/tts.mp3',NOW()),
                                                                 ('개발자 취업을 준비하는 분들을 위한 실전 팁을 공유합니다. 이력서 작성 시 프로젝트 경험을 구체적으로 기술하고, 기술 스택은 실제 사용 가능한 것만 작성하세요. 포트폴리오는 GitHub에 정리하고, 코드 품질에 신경 쓰세요. 면접 준비는 기술 면접과 인성 면접을 나누어 준비하고, 예상 질문에 대한 답변을 미리 준비하세요.', NOW(), 'https://s3/tts-url/tts.mp3',NOW()),
                                                                 ('React 18에서 새롭게 추가된 기능들을 소개합니다. Concurrent Rendering으로 UI 업데이트 성능이 대폭 향상되었습니다. Automatic Batching으로 여러 상태 업데이트를 자동으로 배치 처리합니다. Suspense for Data Fetching을 사용하면 비동기 데이터 로딩을 더 쉽게 처리할 수 있습니다. 실전 예제 코드와 함께 마이그레이션 가이드를 제공합니다.', NOW(), 'https://s3/tts-url/tts.mp3',NOW()),
                                                                 ('블랙프라이데이 특별 세일이 시작되었습니다! 1년 중 가장 큰 할인 행사를 놓치지 마세요. 전 품목 최대 80% 할인과 함께 추가 쿠폰을 제공합니다. 오늘 하루만 적용되는 타임 특가도 준비되어 있습니다. 자정까지만 진행되니 서둘러 주세요!', NOW(), 'https://s3/tts-url/tts.mp3',NOW()),
                                                                 ('마이크로서비스 아키텍처 설계 시 고려해야 할 사항들을 정리했습니다. 서비스 분리 기준, API Gateway 패턴, 서비스 간 통신 방법, 데이터 관리 전략 등을 다룹니다. Spring Cloud, Netflix OSS 등의 도구를 활용한 실제 구현 방법도 소개합니다. 분산 시스템의 복잡도를 관리하는 방법과 모니터링 전략도 함께 설명합니다.', NOW(), 'https://s3/tts-url/tts.mp3',NOW()),
                                                                 ('TypeScript를 처음 시작하는 분들을 위한 완벽 가이드입니다. 타입 시스템의 기본부터 고급 기능까지 체계적으로 학습할 수 있습니다. 인터페이스, 제네릭, 유니온 타입, 타입 가드 등 핵심 개념을 예제와 함께 설명합니다. JavaScript 프로젝트를 TypeScript로 마이그레이션하는 방법도 단계별로 안내합니다.', NOW(), 'https://s3/tts-url/tts.mp3',NOW()),
                                                                 ('2025년 IT 업계의 주요 트렌드를 전망합니다. AI와 머신러닝이 더욱 보편화되고, 엣지 컴퓨팅이 성장할 것으로 예상됩니다. 클라우드 네이티브 기술이 표준이 되고, 개발자 경험(DX) 향상을 위한 도구들이 발전할 것입니다. 보안과 프라이버시에 대한 관심도 높아질 전망입니다. 각 트렌드별 전망과 함께 준비 방법을 제시합니다.', NOW(), 'https://s3/tts-url/tts.mp3',NOW());

-- Article 더미 데이터 (20개) - article_detail'https://s3/tts-url/tts.mp3'_id로 연결
INSERT INTO article (origin_link, publish_date, title, description, image_url, article_category, article_detail_id, created_at, updated_at) VALUES
                                                                                                                                                ('https://news.example.com/1', '2025-10-01 10:30:00', '코레일 추석 예매 사이트 먹통...해결책은?', '추석 기차표 예매 사이트 접속 장애 발생', 'https://example.com/image1.jpg', 'IT', 1, NOW(), NOW()),
                                                                                                                                                ('https://ad.example.com/2', '2025-10-02 11:00:00', '무릎게 최대 20% 줄였다', '건강 보조 식품 특가 할인', 'https://example.com/image2.jpg', '경제', 2, NOW(), NOW()),
                                                                                                                                                ('https://tech.example.com/3', '2025-10-03 09:15:00', 'AI 코딩 도구 비교 분석', 'GitHub Copilot vs ChatGPT vs Claude 비교', 'https://example.com/image3.jpg', 'IT', 3, NOW(), NOW()),
                                                                                                                                                ('https://ad.example.com/4', '2025-10-03 14:20:00', '신제품 출시 안내', '2025년 신상품 라인업 공개', 'https://example.com/image4.jpg', '경제', 4, NOW(), NOW()),
                                                                                                                                                ('https://tech.example.com/5', '2025-10-04 08:00:00', '스프링 부트 성능 최적화 팁', 'Spring Boot 애플리케이션 성능 향상 방법', 'https://example.com/image5.jpg', 'IT', 5, NOW(), NOW()),
                                                                                                                                                ('https://tech.example.com/6', '2025-09-28 10:00:00', 'Java 17 신규 기능 정리', 'Java 17 LTS 버전 주요 기능 소개', 'https://example.com/image6.jpg', 'IT', 6, NOW(), NOW()),
                                                                                                                                                ('https://ad.example.com/7', '2025-09-29 11:30:00', '가을 시즌 특가 세일', '가을맞이 전 상품 할인 행사', 'https://example.com/image7.jpg', '경제', 7, NOW(), NOW()),
                                                                                                                                                ('https://tech.example.com/8', '2025-09-30 09:00:00', 'Docker 컨테이너 최적화', 'Docker 이미지 크기 줄이기 실전 가이드', 'https://example.com/image8.jpg', 'IT', 8, NOW(), NOW()),
                                                                                                                                                ('https://qna.example.com/9', '2025-09-30 14:00:00', 'ChatGPT 활용 가이드', 'ChatGPT를 활용한 업무 생산성 향상', 'https://example.com/image9.jpg', 'IT', 9, NOW(), NOW()),
                                                                                                                                                ('https://news.example.com/10', '2025-10-01 08:30:00', '신상품 라인업 공개', '2025년 하반기 신제품 발표', 'https://example.com/image10.jpg', 'IT', 10, NOW(), NOW()),
                                                                                                                                                ('https://tech.example.com/11', '2025-10-01 16:00:00', 'Kubernetes 입문 가이드', 'K8s 초보자를 위한 완벽 가이드', 'https://example.com/image11.jpg', 'IT', 11, NOW(), NOW()),
                                                                                                                                                ('https://qna.example.com/12', '2025-10-02 09:30:00', '프로그래밍 학습 로드맵', '개발자 커리어 성장 가이드', 'https://example.com/image12.jpg', 'IT', 12, NOW(), NOW()),
                                                                                                                                                ('https://ad.example.com/13', '2025-10-02 13:00:00', '연말 결산 세일 안내', '2025년 연말 특가 행사', 'https://example.com/image13.jpg', '경제', 13, NOW(), NOW()),
                                                                                                                                                ('https://tech.example.com/14', '2025-10-03 10:30:00', 'GraphQL vs REST API', 'API 설계 방식 비교 분석', 'https://example.com/image14.jpg', 'IT', 14, NOW(), NOW()),
                                                                                                                                                ('https://qna.example.com/15', '2025-10-03 15:30:00', '개발자 취업 준비 팁', '신입 개발자 취업 성공 전략', 'https://example.com/image15.jpg', 'IT', 15, NOW(), NOW()),
                                                                                                                                                ('https://tech.example.com/16', '2025-10-04 09:00:00', 'React 18 새로운 기능', 'React 18 주요 업데이트 정리', 'https://example.com/image16.jpg', 'IT', 16, NOW(), NOW()),
                                                                                                                                                ('https://ad.example.com/17', '2025-10-04 11:30:00', '블랙프라이데이 특가', '블랙프라이데이 최대 80% 할인', 'https://example.com/image17.jpg', '경제', 17, NOW(), NOW()),
                                                                                                                                                ('https://tech.example.com/18', '2025-10-04 14:00:00', '마이크로서비스 아키텍처 설계', 'MSA 설계 패턴과 베스트 프랙티스', 'https://example.com/image18.jpg', 'IT', 18, NOW(), NOW()),
                                                                                                                                                ('https://tech.example.com/19', '2025-10-04 16:30:00', 'TypeScript 완벽 가이드', 'TypeScript 기초부터 고급까지', 'https://example.com/image19.jpg', 'IT', 19, NOW(), NOW()),
                                                                                                                                                ('https://news.example.com/20', '2025-10-04 18:00:00', '2025년 IT 트렌드 전망', '내년 IT 산업 전망과 기술 트렌드', 'https://example.com/image20.jpg', 'IT', 20, NOW(), NOW());